# NumPy

In [41]:
#import library
import numpy as np
from numpy import random

In [42]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr = np.array([[11,12,13,14],[1,2,3,4]])
arr

array([[11, 12, 13, 14],
       [ 1,  2,  3,  4]])

In [44]:
#dimention of the array

arr.ndim

2

In [45]:
#shape of the array
arr.shape

(2, 4)

In [46]:
type(arr)

numpy.ndarray

In [47]:
#memory location
arr.data

# Rendom Number Genrator using numpy

In [48]:
x= random.randint(2000)
x

610

In [49]:
#Genrate random Float

x= random.rand()
x

0.314514217423966

In [50]:
x= random.rand(5)
x

array([0.16319511, 0.81211821, 0.26544833, 0.93372336, 0.8800449 ])

In [51]:
x= random.randint(100, size=(5))
x

array([40, 44, 22, 93, 47])

In [52]:
x= random.randint(100, size=(5))
print(x)

[96 48  8 87 24]


In [53]:
x= random.randint(100, size=(3,5))
x

array([[73, 75, 13, 35, 28],
       [72, 72, 19, 90, 98],
       [67, 15,  9, 34, 11]])

In [54]:
x.ndim

2

# x=10 Random integer array 0 to 1000
# y=10 Random integer array 0 to 500
# Math Opration

In [55]:
x= random.randint(1000, size=(10))
x

array([374, 599, 471, 259, 408, 526, 559,  73, 161, 836])

In [56]:
y= random.randint(500, size=(10))
y

array([356, 222, 396, 417, 465,  95,  35, 106,  41, 103])

In [57]:
z= x+y
z

array([730, 821, 867, 676, 873, 621, 594, 179, 202, 939])

In [58]:
z=x-y
z

array([  18,  377,   75, -158,  -57,  431,  524,  -33,  120,  733])

In [59]:
z= x*y
print(z)

[133144 132978 186516 108003 189720  49970  19565   7738   6601  86108]


In [60]:
z= x/y
z

array([ 1.0505618 ,  2.6981982 ,  1.18939394,  0.62110312,  0.87741935,
        5.53684211, 15.97142857,  0.68867925,  3.92682927,  8.11650485])

In [61]:
z= x**y
z

array([          0, -1495306639,  -414377375,   190326403,           0,
                 0,  -732704369, -1577148143,  1529506209,           0],
      dtype=int32)

# creating Matrix

In [62]:
a= np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [65]:
#array like input
b= np.matrix([[5,6,7], [4,6,7]])
b

matrix([[5, 6, 7],
        [4, 6, 7]])

# Measurment of Central Tendancy using numpy

In [68]:
arr= np.array([[1,23,22], [2,35,62], [4,5,6]])
print(arr)
arr.shape

[[ 1 23 22]
 [ 2 35 62]
 [ 4  5  6]]


(3, 3)

In [78]:
np.amin(arr) #minimum value

1

In [79]:
np.amax(arr) #maximum value

62

In [80]:
np.mean(arr) #mean

17.77777777777778

In [81]:
np.median(arr) #median

6.0

In [82]:
np.std(arr) #standerd

19.205194770499972

In [83]:
np.var(arr) #varian

368.8395061728395